name: mbfteam
version: '1.0-SNAPSHOT'
main: net.enabify.mbfteam.Mbfteam
api-version: '1.20'
folia-supported: true

commands:
  mbfteam:
    description: チーム管理コマンド
    usage: /mbfteam <join|leave|tp|list|start|end>
permissions:
  mbfteam.admin:
    description: Allows usage of the MBFTeam commands.
    default: op